import {
  allowCors,
  readJsonBody,
  requirePost,
  sendJson,
} from '../../_lib/aiGuard.js';

const SEARCH_CACHE_TTL = 5 * 60 * 1000;
const DEFAULT_MAX_RESULTS = 16;
const MAX_SEARCH_RESULTS = 20;
const MUSIC_POSITIVE_TERMS = [
  'official audio',
  'official music video',
  'lyrics',
  'lyric video',
  'topic',
  'vevo',
  'provided to youtube by',
  'auto-generated by youtube',
  'official',
  'music',
  'song',
];
const MUSIC_NEGATIVE_TERMS = [
  'reaction',
  'cover',
  'karaoke',
  'tutorial',
  'lesson',
  'live stream',
  'livestream',
  'interview',
  'podcast',
  'vlog',
  'news',
  'shorts',
  'tiktok',
];
const STYLE_TERMS = ['remix', 'slowed', 'nightcore'];
const LONG_INTENT_TERMS = ['mix', 'playlist', 'lofi', 'study', 'sleep', 'chill', 'live'];

const searchCache = globalThis.__luMusicSearchCache ?? new Map();
globalThis.__luMusicSearchCache = searchCache;

export default async function handler(req, res) {
  if (allowCors(req, res)) return;
  if (!requirePost(req, res)) return;

  try {
    const body = await readJsonBody(req);
    const query = typeof body.query === 'string' ? body.query.trim() : '';
    const requestApiKey = typeof body.apiKey === 'string' ? body.apiKey.trim() : '';
    const allowServerKey = process.env.YOUTUBE_ENABLE_SERVER_KEY_FOR_MUSIC === 'true';
    const serverApiKey = allowServerKey
      ? process.env.YOUTUBE_API_KEY || process.env.LUVIDEO_YOUTUBE_API_KEY || ''
      : '';
    const apiKey = requestApiKey || serverApiKey;

    if (!query) {
      sendJson(res, 400, { error: 'Search query cannot be empty.' });
      return;
    }
    if (!apiKey) {
      sendJson(res, 400, { error: 'Missing YouTube API key. Add your key in LuMusic or LuVideo settings.' });
      return;
    }

    const maxResults = Math.min(
      Math.max(Number(body.maxResults) || DEFAULT_MAX_RESULTS, 5),
      MAX_SEARCH_RESULTS,
    );
    const cacheKey = `${query.toLowerCase()}:${maxResults}`;
    const cached = searchCache.get(cacheKey);
    if (cached && Date.now() - cached.createdAt < SEARCH_CACHE_TTL) {
      sendJson(res, 200, cached.payload);
      return;
    }

    const payload = await searchMusic(query, apiKey, maxResults);
    searchCache.set(cacheKey, { createdAt: Date.now(), payload });
    sendJson(res, 200, payload);
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Music search failed.';
    const status = message.includes('quota') || message.includes('rate') ? 429 : 500;
    sendJson(res, status, { error: message });
  }
}

async function searchMusic(query, apiKey, maxResults) {
  const expandedQueries = buildQueryExpansion(query);
  const longIntent = hasAnyTerm(query, LONG_INTENT_TERMS);
  const rawItems = [];

  const primaryItems = await searchYouTube(expandedQueries[0], apiKey, 12, longIntent);
  rawItems.push(...primaryItems);

  const primaryTracks = await hydrateAndRank(rawItems, query, apiKey, longIntent);
  if (primaryTracks.filter((track) => track.score >= 25).length < 6) {
    for (const expandedQuery of expandedQueries.slice(1, 3)) {
      rawItems.push(...await searchYouTube(expandedQuery, apiKey, 8, longIntent));
    }
  }

  const tracks = dedupeTracks(await hydrateAndRank(rawItems, query, apiKey, longIntent))
    .sort((a, b) => b.score - a.score)
    .slice(0, maxResults);

  return {
    tracks,
    weak: tracks.length === 0 || tracks[0].score < 28,
    notice:
      tracks.length === 0 || tracks[0].score < 28
        ? 'Search results may be limited because YouTube Music does not provide an official public API.'
        : '',
  };
}

function buildQueryExpansion(query) {
  const base = query.trim();
  return [
    base,
    `${base} official audio`,
    `${base} lyrics`,
    `${base} topic`,
    `${base} song`,
    `${base} music`,
    `${base} official music video`,
  ];
}

async function searchYouTube(query, apiKey, maxResults, longIntent) {
  const url = new URL('https://www.googleapis.com/youtube/v3/search');
  url.searchParams.set('part', 'snippet');
  url.searchParams.set('q', query);
  url.searchParams.set('type', 'video');
  url.searchParams.set('videoCategoryId', '10');
  url.searchParams.set('videoEmbeddable', 'true');
  url.searchParams.set('videoDuration', longIntent ? 'long' : 'any');
  url.searchParams.set('maxResults', String(maxResults));
  url.searchParams.set('safeSearch', 'none');
  url.searchParams.set('key', apiKey);

  const response = await fetch(url);
  const data = await response.json();
  if (!response.ok || data.error) {
    throw new Error(getYouTubeErrorMessage(data.error));
  }

  return Array.isArray(data.items) ? data.items : [];
}

async function hydrateAndRank(items, query, apiKey, longIntent) {
  const ids = [...new Set(items.map((item) => item.id?.videoId).filter(Boolean))];
  if (ids.length === 0) return [];

  const details = await fetchVideoDetails(ids, apiKey);
  const detailMap = new Map(details.map((item) => [item.id, item]));

  return items
    .map((item) => {
      const videoId = item.id?.videoId;
      if (!videoId) return null;
      const detail = detailMap.get(videoId);
      const snippet = item.snippet || {};
      const durationSeconds = parseIsoDuration(detail?.contentDetails?.duration || '');
      const title = decodeHtml(snippet.title || '');
      const channelTitle = decodeHtml(snippet.channelTitle || '');
      const description = decodeHtml(snippet.description || '');
      const scoreResult = scoreMusicResult({
        title,
        channelTitle,
        description,
        query,
        durationSeconds,
        viewCount: Number(detail?.statistics?.viewCount || 0),
        embeddable: detail?.status?.embeddable !== false,
        longIntent,
      });

      if (detail?.status?.embeddable === false) return null;

      return {
        id: videoId,
        videoId,
        title,
        channelTitle,
        thumbnail:
          snippet.thumbnails?.high?.url ||
          snippet.thumbnails?.medium?.url ||
          snippet.thumbnails?.default?.url ||
          '',
        duration: formatDuration(durationSeconds),
        durationSeconds,
        url: `https://www.youtube.com/watch?v=${videoId}`,
        score: scoreResult.score,
        reason: scoreResult.reason,
      };
    })
    .filter(Boolean);
}

async function fetchVideoDetails(videoIds, apiKey) {
  const url = new URL('https://www.googleapis.com/youtube/v3/videos');
  url.searchParams.set('part', 'contentDetails,status,statistics');
  url.searchParams.set('id', videoIds.slice(0, 50).join(','));
  url.searchParams.set('key', apiKey);

  const response = await fetch(url);
  const data = await response.json();
  if (!response.ok || data.error) {
    throw new Error(getYouTubeErrorMessage(data.error));
  }

  return Array.isArray(data.items) ? data.items : [];
}

function scoreMusicResult({
  title,
  channelTitle,
  description,
  query,
  durationSeconds,
  viewCount,
  embeddable,
  longIntent,
}) {
  const haystack = `${title} ${channelTitle} ${description}`.toLowerCase();
  const normalizedQuery = query.toLowerCase();
  const reasons = [];
  let score = embeddable ? 10 : -50;

  for (const term of MUSIC_POSITIVE_TERMS) {
    if (haystack.includes(term)) {
      score += term === 'music' || term === 'song' ? 4 : 10;
      if (reasons.length < 2) reasons.push(term);
    }
  }

  if (channelTitle.toLowerCase().endsWith(' - topic')) {
    score += 22;
    reasons.push('artist topic channel');
  }
  if (channelTitle.toLowerCase().includes('vevo')) {
    score += 16;
    reasons.push('VEVO');
  }
  if (channelTitle.toLowerCase().includes('official')) {
    score += 10;
    reasons.push('official channel');
  }

  for (const term of MUSIC_NEGATIVE_TERMS) {
    if (haystack.includes(term)) score -= 18;
  }

  for (const style of STYLE_TERMS) {
    if (haystack.includes(style) && !normalizedQuery.includes(style)) score -= 12;
  }

  if (durationSeconds > 0) {
    if (durationSeconds < 60) score -= 24;
    else if (!longIntent && durationSeconds >= 120 && durationSeconds <= 480) score += 16;
    else if (!longIntent && durationSeconds > 600) score -= 24;
    else if (longIntent && durationSeconds > 480) score += 10;
  }

  if (viewCount > 0) {
    score += Math.min(14, Math.log10(viewCount));
  }

  return {
    score: Math.round(score),
    reason: reasons.slice(0, 3).join(' | ') || 'music category match',
  };
}

function dedupeTracks(tracks) {
  const byVideoId = new Map();
  const byTitle = new Map();

  for (const track of tracks) {
    const titleKey = normalizeTitle(track.title);
    const existingById = byVideoId.get(track.videoId);
    const existingByTitle = byTitle.get(titleKey);
    const existing = existingById || existingByTitle;

    if (!existing || track.score > existing.score) {
      byVideoId.set(track.videoId, track);
      byTitle.set(titleKey, track);
    }
  }

  return [...new Set([...byTitle.values(), ...byVideoId.values()])];
}

function normalizeTitle(title) {
  return title
    .toLowerCase()
    .replace(/\([^)]*\)|\[[^\]]*]/g, '')
    .replace(/official|audio|video|lyrics?|lyric|music|song|hd|hq/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

function hasAnyTerm(query, terms) {
  const normalized = query.toLowerCase();
  return terms.some((term) => normalized.includes(term));
}

function parseIsoDuration(value) {
  const match = value.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
  if (!match) return 0;
  const hours = Number(match[1] || 0);
  const minutes = Number(match[2] || 0);
  const seconds = Number(match[3] || 0);
  return hours * 3600 + minutes * 60 + seconds;
}

function formatDuration(seconds) {
  if (!seconds) return '';
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const rest = seconds % 60;
  if (hours > 0) return `${hours}:${String(minutes).padStart(2, '0')}:${String(rest).padStart(2, '0')}`;
  return `${minutes}:${String(rest).padStart(2, '0')}`;
}

function decodeHtml(value) {
  return String(value)
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>');
}

function getYouTubeErrorMessage(error) {
  const message = String(error?.message || '').toLowerCase();
  const reason = String(error?.errors?.[0]?.reason || '').toLowerCase();
  if (message.includes('quota') || reason.includes('quota')) {
    return 'YouTube API quota reached. Try again later.';
  }
  if (message.includes('api key') || reason.includes('key') || reason.includes('forbidden')) {
    return 'Missing YOUTUBE_API_KEY.';
  }
  return error?.message || 'YouTube music search failed.';
}
